/**
 * PDF Export Utility
 *
 * Exports conversations to PDF using the browser's print functionality.
 * Creates a clean, printable HTML document and opens it in a new window for printing.
 */

interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp?: string;
}

interface ExportOptions {
  title: string;
  messages: Message[];
  includeTimestamps?: boolean;
  darkMode?: boolean;
}

/**
 * Generate HTML content for the PDF export
 */
function generatePdfHtml(options: ExportOptions): string {
  const { title, messages, includeTimestamps = true, darkMode = false } = options;

  const bgColor = darkMode ? '#1a1a1a' : '#ffffff';
  const textColor = darkMode ? '#e5e5e5' : '#1a1a1a';
  const userBgColor = darkMode ? '#3b82f6' : '#e0e7ff';
  const userTextColor = darkMode ? '#ffffff' : '#1e40af';
  const assistantBgColor = darkMode ? '#27272a' : '#f3f4f6';
  const borderColor = darkMode ? '#3f3f46' : '#e5e7eb';

  const messagesHtml = messages.map(msg => {
    const isUser = msg.role === 'user';
    const roleLabel = isUser ? 'You' : 'AI Assistant';
    const timestamp = includeTimestamps && msg.timestamp
      ? `<span class="timestamp">${new Date(msg.timestamp).toLocaleString()}</span>`
      : '';

    return `
      <div class="message ${msg.role}">
        <div class="message-header">
          <span class="role">${roleLabel}</span>
          ${timestamp}
        </div>
        <div class="message-content">${escapeHtml(msg.content)}</div>
      </div>
    `;
  }).join('');

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} - aiMate Export</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background-color: ${bgColor};
      color: ${textColor};
      line-height: 1.6;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }

    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 2px solid ${borderColor};
    }

    .header h1 {
      font-size: 24px;
      font-weight: 600;
      margin-bottom: 8px;
    }

    .header .subtitle {
      color: #6b7280;
      font-size: 14px;
    }

    .messages {
      display: flex;
      flex-direction: column;
      gap: 20px;
    }

    .message {
      padding: 16px;
      border-radius: 12px;
      page-break-inside: avoid;
    }

    .message.user {
      background-color: ${userBgColor};
      color: ${userTextColor};
      margin-left: 40px;
    }

    .message.assistant {
      background-color: ${assistantBgColor};
      margin-right: 40px;
    }

    .message-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 8px;
      font-size: 12px;
    }

    .role {
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    .timestamp {
      color: #9ca3af;
    }

    .message-content {
      white-space: pre-wrap;
      word-wrap: break-word;
    }

    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid ${borderColor};
      text-align: center;
      font-size: 12px;
      color: #9ca3af;
    }

    @media print {
      body {
        padding: 20px;
      }

      .message {
        break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(title)}</h1>
    <div class="subtitle">Exported from aiMate on ${new Date().toLocaleDateString()}</div>
  </div>

  <div class="messages">
    ${messagesHtml}
  </div>

  <div class="footer">
    Generated by aiMate - Your AI Mate
  </div>
</body>
</html>
  `;
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Export conversation to PDF by opening a print dialog
 */
export function exportToPdf(options: ExportOptions): void {
  const html = generatePdfHtml(options);

  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    console.error('Failed to open print window. Please allow popups.');
    return;
  }

  printWindow.document.write(html);
  printWindow.document.close();

  // Wait for content to load then print
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };
}

/**
 * Export conversation to JSON file
 */
export function exportToJson(options: ExportOptions): void {
  const { title, messages } = options;
  const data = {
    title,
    exportedAt: new Date().toISOString(),
    messages: messages.map(m => ({
      role: m.role,
      content: m.content,
      timestamp: m.timestamp,
    })),
  };

  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  downloadBlob(blob, `${sanitizeFilename(title)}.json`);
}

/**
 * Export conversation to Markdown file
 */
export function exportToMarkdown(options: ExportOptions): void {
  const { title, messages, includeTimestamps = true } = options;

  let markdown = `# ${title}\n\n`;
  markdown += `*Exported from aiMate on ${new Date().toLocaleDateString()}*\n\n---\n\n`;

  messages.forEach(msg => {
    const roleLabel = msg.role === 'user' ? '**You**' : '**AI Assistant**';
    const timestamp = includeTimestamps && msg.timestamp
      ? ` *(${new Date(msg.timestamp).toLocaleString()})*`
      : '';

    markdown += `${roleLabel}${timestamp}\n\n${msg.content}\n\n---\n\n`;
  });

  const blob = new Blob([markdown], { type: 'text/markdown' });
  downloadBlob(blob, `${sanitizeFilename(title)}.md`);
}

/**
 * Download a blob as a file
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Sanitize filename for safe file system usage
 */
function sanitizeFilename(name: string): string {
  return name
    .replace(/[<>:"/\\|?*]/g, '')
    .replace(/\s+/g, '_')
    .substring(0, 100);
}
